### ISSUE TITLE
TypeScript tests are not working

### ISSUE THREAD

**Issue by klzns** [vtex/test-tools#1]
It throws an error of missing `@types/jest`.

I tried to solve this issue:
- Placing `tsconfig.json` in the user `react` folder
- Placing `tsconfig.json` in the test-tools folder
- Using tsConfig option of `ts-jest` https://kulshekhar.github.io/ts-jest/user/config/tsConfig

None worked.

I'm considering replacing `ts-jest` with the babelTransform, just like create-react-app does.

**Comment by victorhmp** [comment]
Opened a PR to address this :)
